//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertUser
    {
        public decimal Aid { get; set; }
        public Nullable<decimal> MobileNo { get; set; }
        public string Email { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal SMobl { get; set; }
        public string SendSumm { get; set; }
        public int UserID { get; set; }
    }
}
