//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditRetailerAllocation
    {
        public decimal ID { get; set; }
        public decimal AuditId { get; set; }
        public decimal RetailerID { get; set; }
        public decimal ExecutiveID { get; set; }
        public string ConfirmStatus { get; set; }
        public Nullable<System.DateTime> AuditConfirmDate { get; set; }
        public string GeoLocation { get; set; }
        public string DisplayStatus { get; set; }
        public Nullable<System.DateTime> DisplayDate { get; set; }
        public string DisplayImagePath { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public Nullable<decimal> Taskid { get; set; }
        public string Remarks { get; set; }
    }
}
