//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerData
    {
        public string Customer_Posting_Group { get; set; }
        public string No_ { get; set; }
        public string Name { get; set; }
        public string Name_2 { get; set; }
        public string Address { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string Contact { get; set; }
        public string Phone_No_ { get; set; }
        public string Phone_No_2 { get; set; }
        public string Branch_Code { get; set; }
        public string Salesperson_Code { get; set; }
        public decimal Id { get; set; }
        public decimal ExecutiveId { get; set; }
    }
}
