//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributorList
    {
        public string No_ { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string STATE { get; set; }
        public string Contact { get; set; }
        public Nullable<double> Phone_No_ { get; set; }
        public Nullable<double> Phone_No_2 { get; set; }
        public string Customer_Posting_Group { get; set; }
        public string Salesperson_Code { get; set; }
        public int StateCode { get; set; }
        public int CityCode { get; set; }
        public int DistID { get; set; }
        public int ExecID { get; set; }
    }
}
