//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributorSummary
    {
        public string DistributorNm { get; set; }
        public string ContactPerson { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<double> Pincode { get; set; }
        public Nullable<double> PhNo { get; set; }
        public Nullable<double> Mobile_No_ { get; set; }
        public string UserID { get; set; }
        public Nullable<double> Passw { get; set; }
        public string IsActive { get; set; }
        public string Area_Email_Id_1 { get; set; }
        public string Area_Email_Id_2 { get; set; }
        public int ID { get; set; }
    }
}
