//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_DSRMaster
    {
        public decimal ID { get; set; }
        public decimal ExecutiveID { get; set; }
        public decimal RetailerID { get; set; }
        public string RetailerNm { get; set; }
        public Nullable<System.DateTime> DSRDt { get; set; }
        public string Purpose { get; set; }
        public Nullable<decimal> OrderPcs { get; set; }
        public decimal OrderValue { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal Amount { get; set; }
        public string Location { get; set; }
        public string Activity { get; set; }
        public string LastLocation { get; set; }
        public string Distance { get; set; }
    }
}
