//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ProductMaster
    {
        public decimal Pid { get; set; }
        public Nullable<decimal> RangeId { get; set; }
        public string PCode { get; set; }
        public string PName { get; set; }
        public string PImage1 { get; set; }
        public string PImage2 { get; set; }
        public string PImage3 { get; set; }
        public string PImage4 { get; set; }
        public Nullable<decimal> PDescID { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> PSizeID { get; set; }
        public Nullable<decimal> PColorID { get; set; }
        public string MaterialCode { get; set; }
        public string Videopath { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RectimeStamp { get; set; }
        public decimal MasterID { get; set; }
    }
}
