//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_SubGroupMaster
    {
        public decimal Aid { get; set; }
        public decimal GroupID { get; set; }
        public decimal SubGroupID { get; set; }
        public string SubGroupNm { get; set; }
        public string ActiveStatus { get; set; }
    }
}
