//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_UserPermissionMaster
    {
        public decimal AutoId { get; set; }
        public decimal GroupId { get; set; }
        public decimal MenuId { get; set; }
        public string RowStatus { get; set; }
        public string IPAdrs { get; set; }
        public string MACAdrs { get; set; }
        public string ActiveStatus { get; set; }
    }
}
