//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_UserMaster
    {
        public decimal UId { get; set; }
        public decimal GroupId { get; set; }
        public decimal UserId { get; set; }
        public string UserName { get; set; }
        public string Passw { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string Remarks { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string LastIp { get; set; }
        public string LastLoginTime { get; set; }
        public string LastLogOutTime { get; set; }
        public string Version { get; set; }
        public string LoginStatus { get; set; }
        public string LastModified { get; set; }
        public string UserCode { get; set; }
        public decimal UsrId { get; set; }
        public string RowStatus { get; set; }
        public string IPAdrs { get; set; }
        public string MACAdrs { get; set; }
        public byte[] MemPic { get; set; }
    }
}
