//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_WebMenuMaster
    {
        public decimal AId { get; set; }
        public decimal MenuId { get; set; }
        public string Hierar { get; set; }
        public string MenuName { get; set; }
        public decimal ParentId { get; set; }
        public string OnSelect { get; set; }
        public string ShortKeys { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string LastModified { get; set; }
        public string ActiveStatus { get; set; }
        public string RowStatus { get; set; }
        public string IPAdrs { get; set; }
        public string MACAdrs { get; set; }
    }
}
