//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstAuditTypeMaster
    {
        public decimal TypeId { get; set; }
        public string AuditType { get; set; }
        public string Activestatus { get; set; }
        public decimal UserID { get; set; }
    }
}
