//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstDistExecutive
    {
        public decimal Aid { get; set; }
        public decimal ExecutiveID { get; set; }
        public decimal DistributorID { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
    }
}
