//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_CityMaster
    {
        public int cityID { get; set; }
        public string cityName { get; set; }
        public string stateName { get; set; }
        public Nullable<int> StateId { get; set; }
    }
}
