//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_MessageMaster
    {
        public string Id { get; set; }
        public Nullable<System.DateTime> MessagePublishDate { get; set; }
        public string Header { get; set; }
        public string Message { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> PublishFrom { get; set; }
        public Nullable<System.DateTime> PublishTo { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
