//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_NotificationResult
    {
        public string Id { get; set; }
        public string NotificationId { get; set; }
        public Nullable<decimal> FailMessageCount { get; set; }
        public Nullable<decimal> SuccessMessageCount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> NotificationIdCount { get; set; }
        public string Exception { get; set; }
    }
}
