//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_NotificationManager
    {
        public string Id { get; set; }
        public string Notification { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<bool> IsReplyable { get; set; }
        public Nullable<bool> Boradcast { get; set; }
        public Nullable<int> StateCode { get; set; }
        public Nullable<int> CityCode { get; set; }
        public string Header { get; set; }
    }
}
