//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_OrderMaster
    {
        public string Id { get; set; }
        public string ProductId { get; set; }
        public string RetailerId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> PointsUsed { get; set; }
        public string OrderStatus { get; set; }
        public string OrderNo { get; set; }
        public string ProductName { get; set; }
        public string RetailerName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
    }
}
