//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_Promotion
    {
        public string Id { get; set; }
        public string Heading { get; set; }
        public string HeadingText { get; set; }
        public Nullable<int> ImageCount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Image { get; set; }
        public Nullable<int> TotalEntries { get; set; }
        public Nullable<int> Points { get; set; }
    }
}
