//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_ProductMaster
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public Nullable<long> Points { get; set; }
        public Nullable<long> Quantity { get; set; }
        public string ProductCode { get; set; }
        public string Size { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
