//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_RetailerMaster
    {
        public string ID { get; set; }
        public string DistributorId { get; set; }
        public string FirmName { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string StateId { get; set; }
        public string CityId { get; set; }
        public string PinCode { get; set; }
        public string ProfilePicture { get; set; }
        public string ShopLogo { get; set; }
        public string ShopGpsX { get; set; }
        public string ShopGpsY { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Password { get; set; }
        public string DistributerName { get; set; }
        public string DistributerCity { get; set; }
        public string DistributerMobileNo { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string AddressGpsX { get; set; }
        public string AddressGpsY { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string NotificationId { get; set; }
        public string StateName { get; set; }
        public string CityName { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public Nullable<decimal> Points { get; set; }
        public string IsBlock { get; set; }
    }
}
