//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesPerson
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Block { get; set; }
        public Nullable<double> Commission__ { get; set; }
        public string Branch_Code { get; set; }
        public string E_Mail { get; set; }
        public Nullable<double> Phone_No_ { get; set; }
        public int Id { get; set; }
    }
}
