//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegistration
    {
        public int RegId { get; set; }
        public string FirmName { get; set; }
        public string RetailerName { get; set; }
        public string RetailerAddress { get; set; }
        public string ShippingAddress { get; set; }
        public Nullable<decimal> StateCode { get; set; }
        public string MobileNo { get; set; }
        public Nullable<decimal> CityCode { get; set; }
        public string Pincode { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsApprove { get; set; }
    }
}
