//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempCompanyMaster
    {
        public decimal CId { get; set; }
        public decimal CompId { get; set; }
        public string CompName { get; set; }
        public string CompAdd { get; set; }
        public string CompState { get; set; }
        public string CompCity { get; set; }
        public string CompTinNo { get; set; }
        public string CompPhNo { get; set; }
        public string CompMail { get; set; }
        public string CompTitle { get; set; }
        public string WebSite { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string smsUrl { get; set; }
        public string smsSenderId { get; set; }
        public string smsUserNm { get; set; }
        public string smsPassw { get; set; }
        public string MailHost { get; set; }
        public string MailUser { get; set; }
        public string MailPassw { get; set; }
        public decimal StateCode { get; set; }
        public decimal CityCode { get; set; }
        public decimal MailPort { get; set; }
        public string Prefix { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> ActionOn { get; set; }
        public Nullable<decimal> ByUserID { get; set; }
    }
}
