//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempAuditMaster
    {
        public decimal AuditId { get; set; }
        public string AuditDescription { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> AuditQueDate { get; set; }
        public Nullable<System.DateTime> AuditExpiryDate { get; set; }
        public string Activestatus { get; set; }
        public decimal Points { get; set; }
        public Nullable<System.DateTime> RectTimeStamp { get; set; }
        public decimal TypeID { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> ActionOn { get; set; }
        public Nullable<decimal> ActionBy { get; set; }
    }
}
