//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempDistributorMaster
    {
        public decimal Mid { get; set; }
        public decimal DistributorId { get; set; }
        public string DistributorNm { get; set; }
        public string ContactPerson { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PinCode { get; set; }
        public string PhNo { get; set; }
        public string FaxNo { get; set; }
        public decimal Mobl { get; set; }
        public System.DateTime Doj { get; set; }
        public string EMail { get; set; }
        public string ActiveStatus { get; set; }
        public string UserId { get; set; }
        public string Passw { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal DailyPCs { get; set; }
        public decimal DailyStore { get; set; }
        public decimal WeeklyPCs { get; set; }
        public decimal WeeklyStore { get; set; }
        public decimal MonthlyPCs { get; set; }
        public decimal MonthlyStore { get; set; }
        public decimal QuarterlyPCs { get; set; }
        public decimal QuarterlyStore { get; set; }
        public decimal HalfYearlyPCs { get; set; }
        public decimal HalfYearlyStore { get; set; }
        public decimal YearlyPCs { get; set; }
        public decimal YearlyStore { get; set; }
        public decimal StateCode { get; set; }
        public decimal CityCode { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> ActionOn { get; set; }
        public Nullable<decimal> ByUserID { get; set; }
    }
}
