//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempRetailerMaster
    {
        public decimal Mid { get; set; }
        public decimal RetailerId { get; set; }
        public decimal DistributorId { get; set; }
        public decimal ExecutiveId { get; set; }
        public string FirmName { get; set; }
        public string ContactPerson { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PinCode { get; set; }
        public string PhNo { get; set; }
        public string Fax { get; set; }
        public decimal Mobl { get; set; }
        public System.DateTime Doj { get; set; }
        public string EMail { get; set; }
        public string ActiveStatus { get; set; }
        public string UserId { get; set; }
        public string Passw { get; set; }
        public string HostIp { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string RetailerCode { get; set; }
        public decimal StateCode { get; set; }
        public decimal CityCode { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> ActionOn { get; set; }
        public Nullable<decimal> ByUserID { get; set; }
    }
}
