//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempProduct
    {
        public decimal TID { get; set; }
        public decimal Pid { get; set; }
        public decimal GroupID { get; set; }
        public decimal SubGroupID { get; set; }
        public string PCode { get; set; }
        public string PName { get; set; }
        public string PDescription { get; set; }
        public string GSTGroup { get; set; }
        public decimal Price { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public string Img1 { get; set; }
        public string Img2 { get; set; }
        public string Img3 { get; set; }
        public string Img4 { get; set; }
        public string MaterialCode { get; set; }
        public string Videopath { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal UserID { get; set; }
        public int MProdID { get; set; }
        public string TRemarks { get; set; }
        public System.DateTime TRecTimeStamp { get; set; }
        public int TUserID { get; set; }
    }
}
