//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnLogin
    {
        public decimal Aid { get; set; }
        public string usernm { get; set; }
        public System.DateTime rectmstamp { get; set; }
        public string passwd { get; set; }
        public string type { get; set; }
    }
}
