//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnOrder
    {
        public decimal ID { get; set; }
        public decimal OrderNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string PartyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public decimal PinCode { get; set; }
        public decimal Mobl { get; set; }
        public string EMail { get; set; }
        public string PhNo { get; set; }
        public string FaxNo { get; set; }
        public decimal RetailerId { get; set; }
        public decimal ExecutiveId { get; set; }
        public Nullable<decimal> DistributorId { get; set; }
        public decimal OrderItem { get; set; }
        public decimal OrderQty { get; set; }
        public decimal OrderAmt { get; set; }
        public string ActiveStatus { get; set; }
        public string IsDelivered { get; set; }
        public string HostIp { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string Remarks { get; set; }
        public decimal StateCode { get; set; }
        public decimal CityCode { get; set; }
        public string dispRemark { get; set; }
    }
}
