//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AuditMaster
    {
        public decimal AuditID { get; set; }
        public string AuditDescription { get; set; }
        public string ImagePath { get; set; }
        public string AuditQueDate { get; set; }
        public string AuditExpiryDate { get; set; }
        public string ActiveStatus { get; set; }
        public decimal Points { get; set; }
        public decimal TypeID { get; set; }
        public string AuditType { get; set; }
        public string IsActive { get; set; }
    }
}
