//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CityStateMaster
    {
        public decimal Aid { get; set; }
        public decimal CityCode { get; set; }
        public string CityName { get; set; }
        public decimal StateCode { get; set; }
        public decimal PinCode { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string IsActive { get; set; }
        public string StateName { get; set; }
    }
}
