//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DSR
    {
        public decimal ID { get; set; }
        public decimal RetailerID { get; set; }
        public decimal ExecutiveID { get; set; }
        public string Purpose { get; set; }
        public string OrderPcs { get; set; }
        public decimal OrderValue { get; set; }
        public string Activity { get; set; }
        public decimal Amount { get; set; }
        public string Location { get; set; }
        public string LastLocation { get; set; }
        public string Distance { get; set; }
        public string DSROn { get; set; }
        public Nullable<System.DateTime> DSRDt { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string FirmName { get; set; }
        public string Addrs { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string DSRBy { get; set; }
        public string DSRUser { get; set; }
        public decimal DistributorID { get; set; }
        public decimal VPID { get; set; }
        public decimal NSMID { get; set; }
        public decimal RSMID { get; set; }
        public decimal ASMID { get; set; }
    }
}
