//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HalfYearlyTarget
    {
        public decimal ExecutiveID { get; set; }
        public string Target { get; set; }
        public Nullable<decimal> Pieces { get; set; }
        public Nullable<decimal> Stores { get; set; }
        public Nullable<decimal> AchHalfYearlyPcs { get; set; }
        public Nullable<int> AchHalfYearlyStore { get; set; }
        public string AchPcs { get; set; }
        public string AchStore { get; set; }
    }
}
