//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MasterProduct
    {
        public decimal ID { get; set; }
        public decimal RangeID { get; set; }
        public string Range { get; set; }
        public decimal PNameID { get; set; }
        public string ProductNm { get; set; }
        public decimal PDescID { get; set; }
        public string Description { get; set; }
        public string PCode { get; set; }
        public decimal Price { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public string SizeID { get; set; }
        public string ColorID { get; set; }
        public string Img1 { get; set; }
        public string Img2 { get; set; }
        public string Img3 { get; set; }
        public string Img4 { get; set; }
        public string VideoPath { get; set; }
        public string MaterialCode { get; set; }
    }
}
