//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MainOrderDetail
    {
        public decimal ID { get; set; }
        public decimal ExecutiveID { get; set; }
        public decimal RetailerID { get; set; }
        public string Pheading { get; set; }
        public Nullable<decimal> DistributorID { get; set; }
        public decimal OrderNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string OrderDt { get; set; }
        public decimal OrderItem { get; set; }
        public decimal OrderQty { get; set; }
        public string PartyName { get; set; }
        public string ShipingAddress { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public decimal PinCode { get; set; }
        public decimal MobileNo { get; set; }
        public string Email { get; set; }
        public string PhNo { get; set; }
        public string FaxNo { get; set; }
        public string isDelivered { get; set; }
        public string Executive { get; set; }
        public string Distributor { get; set; }
        public string DispStatus { get; set; }
        public string Remarks { get; set; }
        public string DispRemark { get; set; }
        public string RetailerCode { get; set; }
        public decimal ProductID { get; set; }
        public string PName { get; set; }
        public decimal Qty { get; set; }
        public string Size { get; set; }
        public string PCode { get; set; }
        public string color { get; set; }
        public string MaterialCode { get; set; }
    }
}
