//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OrderXls
    {
        public decimal OrderNo { get; set; }
        public string OrderDt { get; set; }
        public string RetailerCode { get; set; }
        public string PartyName { get; set; }
        public string ShipingAddress { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public decimal PinCode { get; set; }
        public decimal MobileNo { get; set; }
        public string Email { get; set; }
        public string PhNo { get; set; }
        public string FaxNo { get; set; }
        public string Executive { get; set; }
        public string Distributor { get; set; }
        public string ProductName { get; set; }
        public string StyleNo { get; set; }
        public decimal Qty { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string MaterialCode { get; set; }
        public string OrderRemark { get; set; }
        public string Dispatch { get; set; }
        public string DispatchRemark { get; set; }
    }
}
