//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ProductList_
    {
        public decimal GroupID { get; set; }
        public decimal SubGroupID { get; set; }
        public string PCode { get; set; }
        public string Color { get; set; }
        public decimal Price { get; set; }
        public string PImage1 { get; set; }
        public string PImage2 { get; set; }
        public string PImage3 { get; set; }
        public string PImage4 { get; set; }
        public string VideoPath { get; set; }
        public string PName { get; set; }
        public int MProdID { get; set; }
        public string GroupNm { get; set; }
        public string SubGroupNm { get; set; }
        public string Sizes { get; set; }
    }
}
