//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Tasks
    {
        public decimal ID { get; set; }
        public Nullable<decimal> taskID { get; set; }
        public decimal ExecutiveId { get; set; }
        public decimal RetailerId { get; set; }
        public string FirmName { get; set; }
        public string Address { get; set; }
        public decimal AuditID { get; set; }
        public Nullable<System.DateTime> AuditQueDate { get; set; }
        public Nullable<System.DateTime> AuditExpiryDate { get; set; }
        public string auditDescription { get; set; }
        public decimal auditPoints { get; set; }
        public string Imagepath { get; set; }
        public string ConfirmStatus { get; set; }
        public string DisplayStatus { get; set; }
        public Nullable<System.DateTime> AuditConfirmDate { get; set; }
        public Nullable<System.DateTime> DisplayDate { get; set; }
        public string tasktype { get; set; }
        public decimal typeid { get; set; }
    }
}
